version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ninjasdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: caiojacob/ninjasregister:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ninjasdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data: